all :
	(cd x86 ; make)
	(cd x86-as ; make)
	(cd pdp11 ; make)
	(cd C ; make)
	(cd x86-user ; make)
	(cd x86-sys ; make)
	(cd x86-32 ; make)
	(cd m68k ; make)
	(cd sparc ; make)
	(cd z80 ; make)
	(cd z80-c ; make)
	(cd z180-sdcc ; make)
	(cd z80n-sdcc ; make)
	(cd msp430-as ; make)
	(cd arm-zigcc ; make)
	(cd arm64-sys ; make)
	(cd riscv-zigcc ; make)
	(cd rv64-sys ; make)
	(cd rv32-sys ; make)
	(cd msp430-stc ; make)
	(cd z80-stc ; make)
	(cd msp430-fcode ; make)
	(cd msp430-f ; make)
	(cd nqh-zig ; make)
	(cd wasm32-c ; make)
	(cd pdk14-stc ; make)
	(cd pdk14-thr1 ; make)
	(cd 6502-sdcc ; make)
	(cd 6502-stc ; make)
	(cd f16-zig ; make)
	(cd 8051-sdcc ; make)
	(cd 8051-stc ; make)

allsteps :
	./runallsteps

size : all
	./gensize
clean :
	(cd x86 ; make clean)
	(cd x86-as ; make clean)
	(cd pdp11 ; make clean)
	(cd C ; make clean)
	(cd x86-user ; make clean)
	(cd x86-sys ; make clean)
	(cd x86-32 ; make clean)
	(cd m68k ; make clean)
	(cd sparc ; make clean)
	(cd z80 ; make clean)
	(cd z80-c ; make clean)
	(cd z180-sdcc ; make clean)
	(cd z80n-sdcc ; make clean)
	(cd msp430-as ; make clean)
	(cd arm-zigcc ; make clean)
	(cd arm64-sys ; make clean)
	(cd riscv-zigcc ; make clean)
	(cd rv64-sys ; make clean)
	(cd rv32-sys ; make clean)
	(cd msp430-stc ; make clean)
	(cd z80-stc ; make clean)
	(cd msp430-fcode ; make clean)
	(cd msp430-f ; make clean)
	(cd nqh-zig ; make clean)
	(cd wasm32-c ; make clean)
	(cd pdk14-stc ; make clean)
	(cd pdk14-thr1 ; make clean)
	(cd 6502-sdcc ; make clean)
	(cd 6502-stc ; make clean)
	(cd f16-zig ; make clean)
	(cd 8051-sdcc ; make clean)
	(cd 8051-stc ; make clean)
