#!/usr/bin/perl -w
use strict;

my $step;
my $x=`cat stepfile`;
$x=~s/^/\$/;
eval $x;

my $hash={};
my $list=[0..4,qw(4.1 4.2 4.3),5..9,qw(10.1 10.2 10.3),11..62];
for my $i (@$list) {
	last if ($i>=42);
	$hash->{"$i"}="0x602080";
}
for my $i (42..62) {
	$hash->{"$i"}="0x603080";
}
for my $i (@$list) {
	last if ($i>$step);
	my $a=$hash->{"$i"};
	@ARGV=("fpp.config.C");
	open(my $fh, ">fpp.config");
	select $fh;
	print "step=$i\n";
	while (<>) {
		s/^ADDR=.*/ADDR=$a/;
		s/^VALUE=.*/VALUE=$a/;
		print;
	}
	close $fh;
	select STDOUT;
	print "\nRunning step $i\n";
	system("make") == 0 or die "make failed at step $i with exit status $?"
}
