#!/usr/bin/perl -w

# gendict : generate the dictionary headers
#
# Copyright (c) 2025-2026 Charles Suresh <romforth@proton.me>
# SPDX-License-Identifier: AGPL-3.0-only
# Please see the LICENSE file for the Affero GPL 3.0 license details

use strict;

require("./gencode");

my $x=require("./".shift) or die "parse failed";

my $prev='0';

my $c=$x->{'code'};
my $v=$x->{'var'};

my $p;

my @l=();
while (<>) {
	my ($k,$w,$l)=split;
	last unless ($p=$x->{$k}->{$w});
	if ($k eq 'var') {
		unshift @l, [$w,$p,1];
	} elsif ($k eq 'code') {
		push @l, [$w,$p,0];
	} else {
		last;
	}
}
for my $i (@l) {
	my ($w,$p,$flag)=@$i;
	$prev=fullheader($w,$p,$prev,$flag);
}
