#!/usr/bin/perl -w

# remove stack comments denoted by '['
#
# Copyright (c) 2025 Charles Suresh <romforth@proton.me>
# SPDX-License-Identifier: AGPL-3.0-only
# Please see the LICENSE file for the Affero GPL 3.0 license details

while (<>) {
	s/^\[$// && next;		# standalone picture comment: [
	s/^\[\s+.*$// && next;	# starting comment			: [ 1 2 3
	s/\s+\[$//;				# embedded picture comment	: foo [
	s/\s+\[\s+.*$//;		# trailing comment			: foo [ 1 2 3
	print;
}
