# makefile : drive the build and test for the x86 assembly syscall based code
#
# Copyright (c) 2023 Charles Suresh <romforth@proton.me>
# SPDX-License-Identifier: AGPL-3.0-only
# Please see the LICENSE file for the Affero GPL 3.0 license details

forth : forth.o
	ld -o forth forth.o
clean :
	rm -f forth.o forth
