#!/usr/bin/perl -w

# m2 : a simpler(?) macro processor (m2 == m4/2)
#
# Copyright (c) 2024 Charles Suresh <romforth@proton.me>
# SPDX-License-Identifier: AGPL-3.0-only
# Please see the LICENSE file for the Affero GPL 3.0 license details

use strict;

my ($v,$vv);
my $def={};

my @save=(@ARGV);

@ARGV=("prims.s");

while (<>) {
	if (/^(\S+)\:$/) {
		 $v=\$def->{$1};
		 die "$1 is already defined" if ($vv=$$v);
		 $vv=$$v=[];
	} else {
		 push @$vv, $_;
	}
}

@ARGV=(@save);

while (<>) {
	if (/^\t(\S+)\s*(\;.*)?/) {
		 $v=\$def->{$1};
		 die "$1 is not defined" unless ($vv=$$v);
		 print join("",@$vv);
	} else {
		print;
	}
}
